apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.gitlab.gitlab.gitaly.persistence.name }}
  namespace: {{ .Release.Namespace }}
  labels:
      app: gitaly
spec:
  capacity:
    storage: {{ .Values.gitlab.gitlab.gitaly.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass }}
  local:
    path: {{ .Values.rootDirectory }}/{{ .Release.Namespace }}/{{ .Values.gitlab.gitlab.gitaly.persistence.name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.masterNodeName }}