apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.storageClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true