apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.redis.master.persistence.name }}
  namespace: {{ .Release.Namespace }}
  labels:
      app: redis
spec:
  capacity:
    storage: {{ .Values.redis.master.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.global.storageClass }}
  local:
    path: {{ .Values.rootDirectory }}/{{ .Release.Namespace }}/{{ .Values.redis.master.persistence.name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.masterNodeName }}